{"name": "Авторизаиция с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1745687278582, "stop": 1745687279485}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1745687279485, "stop": 1745687279833}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1745687279833, "stop": 1745687279860}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1745687278581, "stop": 1745687279861, "uuid": "3e9941cc-b61a-4aee-8661-4e2fe59a4369", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Авторизаци"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Elshad27"}, {"name": "thread", "value": "8936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}