{"name": "Авторизаиция с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1745689267439, "stop": 1745689268182}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1745689268182, "stop": 1745689268384}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1745689268384, "stop": 1745689268404}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1745689267439, "stop": 1745689268405, "uuid": "eb8aced8-90af-4b8c-9a89-67b818ecea02", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "feature", "value": "Авторизаци"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Elshad27"}, {"name": "thread", "value": "9632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}